Le nettoyage des données, également appelé nettoyage ou épuration des données, consiste à détecter et à supprimer les erreurs et les incohérences des données afin d’améliorer leur qualité. Les problèmes de qualité des données sont présents dans les données uniques
collections, telles que des fichiers et des bases de données, par exemple, en raison de fautes d’orthographe lors de la saisie de données, d’informations manquantes ou autres données invalides.

Enrichissement du dataset selon les règles

In [11]:
import pandas as pd
import numpy as np

df_original = pd.read_excel("XPON_QUALIF.xlsx")
n_original = len(df_original)

n_to_add = np.random.randint(15000, 20001)

ID_LIGNE_VALUES = df_original['ID_LIGNE'].unique()
ID_CARTE_OLT_VALUES = df_original['ID_CARTE_OLT'].unique()
NO_PORT_VALUES = list(range(1, 17))
ONU_ID_VALUES = list(range(1, 101))

def generate_synthetic_rows(n):
    rows = []

    for _ in range(n):

        category = np.random.choice(
            ['faible', 'bon', 'eleve'],
            p=[0.15, 0.7, 0.15]
        )


        if category == 'faible':
            olt_tx = np.random.uniform(0, 2)
        elif category == 'bon':
            olt_tx = np.random.uniform(2, 7)
        else:
            olt_tx = np.random.uniform(7, 12)


        if category == 'faible':
            olt_rx = np.random.uniform(-40, -32)
        elif category == 'bon':
            olt_rx = np.random.uniform(-32, -12)
        else:
            olt_rx = np.random.uniform(-12, -5)


        if category == 'faible':
            onu_tx = np.random.uniform(0, 2)
        elif category == 'bon':
            onu_tx = np.random.uniform(2, 5)
        else:
            onu_tx = np.random.uniform(5, 10)

        if category == 'faible':
            onu_rx = np.random.uniform(-35, -28)
        elif category == 'bon':
            onu_rx = np.random.uniform(-28, -7)
        else:
            onu_rx = np.random.uniform(-7, 0)

        if np.random.random() < 0.10:
            f_susp = 1
            admin_status = 0 if np.random.random() < 0.8 else 1
        else:
            f_susp = 0
            admin_status = np.random.choice([0, 1])

        oper_status = 0 if (f_susp == 1 or admin_status == 0) else 1

        if np.random.random() < 0.05:
            olt_tx += np.random.uniform(-5, 5)
            onu_rx += np.random.uniform(-10, 10)

        rows.append({
            'ID_LIGNE': np.random.choice(ID_LIGNE_VALUES),
            'ID_CARTE_OLT': np.random.choice(ID_CARTE_OLT_VALUES),
            'NO_PORT': np.random.choice(NO_PORT_VALUES),
            'ONU_ID': np.random.choice(ONU_ID_VALUES),
            'OLT_POWER_TX': round(olt_tx, 2),
            'OLT_RX_ONT_POWER': round(olt_rx, 2),
            'ONU_POWER_TX': round(onu_tx, 2),
            'ONU_POWER_RX': round(onu_rx, 2),
            'F_SUSP': f_susp,
            'ADMIN_STATUS': admin_status,
            'OPER_STATUS': oper_status
        })

    return pd.DataFrame(rows)

df_synthetic = generate_synthetic_rows(n_to_add)

df_final = pd.concat([df_original, df_synthetic], ignore_index=True)

df_final.to_excel("XPON_QUALIF_augmented.xlsx", index=False)

print(f"Dataset original : {n_original} lignes")
print(f"Lignes ajoutées  : {n_to_add} lignes")
print(f"Dataset final   : {len(df_final)} lignes")

Dataset original : 1519 lignes
Lignes ajoutées  : 19365 lignes
Dataset final   : 20884 lignes

Lire le fichier du dataset enrichis

In [12]:
df =pd.read_excel("XPON_QUALIF_augmented.xlsx")
df

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX
0,80881135.0,111.0,3.0,39.0,0.0,1.0,1.0,3.80,-20.70,2.442,-20.268
1,80881064.0,111.0,1.0,26.0,0.0,1.0,1.0,3.50,-20.30,2.522,-18.386
2,83109348.0,151.0,1.0,3.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,83109379.0,111.0,4.0,31.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,83825624.0,111.0,13.0,60.0,0.0,1.0,1.0,3.60,-25.30,2.530,-22.840
...,...,...,...,...,...,...,...,...,...,...,...
20879,80297925.0,20406.0,11.0,40.0,0.0,1.0,1.0,10.39,-11.24,5.250,-5.250
20880,83848003.0,20727.0,16.0,91.0,0.0,0.0,0.0,1.43,-35.32,0.850,-33.680
20881,83110199.0,20499.0,15.0,65.0,0.0,0.0,0.0,4.33,-18.69,2.740,-11.790
20882,83204888.0,163.0,16.0,49.0,0.0,0.0,0.0,6.19,-26.54,2.520,-25.330
20883,83825832.0,20729.0,7.0,58.0,0.0,1.0,1.0,0.82,-38.68,1.670,-29.610

obtenir des informations de dataframe

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20884 entries, 0 to 20883
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_LIGNE          20868 non-null  float64
 1   ID_CARTE_OLT      20531 non-null  float64
 2   NO_PORT           20882 non-null  float64
 3   ONU_ID            20881 non-null  float64
 4   F_SUSP            20882 non-null  float64
 5   ADMIN_STATUS      20882 non-null  float64
 6   OPER_STATUS       20882 non-null  float64
 7   OLT_POWER_TX      20469 non-null  float64
 8   OLT_RX_ONT_POWER  20468 non-null  float64
 9   ONU_POWER_TX      20469 non-null  float64
 10  ONU_POWER_RX      20469 non-null  float64
dtypes: float64(11)
memory usage: 1.8 MB

Vérifiez les valeurs nulles

In [14]:
isnull = df.isnull()

isnull_count = isnull.sum()

print(isnull_count)

total_isnull = isnull.sum().sum()
print("totals null : ", total_isnull)

ID_LIGNE             16
ID_CARTE_OLT        353
NO_PORT               2
ONU_ID                3
F_SUSP                2
ADMIN_STATUS          2
OPER_STATUS           2
OLT_POWER_TX        415
OLT_RX_ONT_POWER    416
ONU_POWER_TX        415
ONU_POWER_RX        415
dtype: int64
totals null :  2041

déposer des valeurs null

In [15]:
df.dropna(inplace=True)

df

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX
0,80881135.0,111.0,3.0,39.0,0.0,1.0,1.0,3.80,-20.70,2.442,-20.268
1,80881064.0,111.0,1.0,26.0,0.0,1.0,1.0,3.50,-20.30,2.522,-18.386
4,83825624.0,111.0,13.0,60.0,0.0,1.0,1.0,3.60,-25.30,2.530,-22.840
8,83847300.0,20309.0,8.0,39.0,1.0,1.0,1.0,3.60,-24.30,2.674,-23.280
9,83109466.0,166.0,2.0,4.0,1.0,1.0,1.0,5.64,-25.86,2.330,-19.660
...,...,...,...,...,...,...,...,...,...,...,...
20879,80297925.0,20406.0,11.0,40.0,0.0,1.0,1.0,10.39,-11.24,5.250,-5.250
20880,83848003.0,20727.0,16.0,91.0,0.0,0.0,0.0,1.43,-35.32,0.850,-33.680
20881,83110199.0,20499.0,15.0,65.0,0.0,0.0,0.0,4.33,-18.69,2.740,-11.790
20882,83204888.0,163.0,16.0,49.0,0.0,0.0,0.0,6.19,-26.54,2.520,-25.330
20883,83825832.0,20729.0,7.0,58.0,0.0,1.0,1.0,0.82,-38.68,1.670,-29.610

compter et afficher les doublons

In [17]:
doublons = df.duplicated()

doublons_count = doublons.sum()

print(doublons_count)
print(df[doublons])

1
        ID_LIGNE  ID_CARTE_OLT  NO_PORT  ONU_ID  F_SUSP  ADMIN_STATUS  \
1516  83110178.0         166.0      2.0    16.0     0.0           1.0

      OPER_STATUS  OLT_POWER_TX  OLT_RX_ONT_POWER  ONU_POWER_TX  ONU_POWER_RX
1516          1.0          5.65            -20.61          2.17         -15.8

supprimer les doublons de dataframe

In [18]:
df = df.drop_duplicates()

obtenir des statistiques de dataframe de les colonnes: "OLT_POWER_TX","OLT_RX_ONT_POWER","ONU_POWER_TX" et "ONU_POWER_RX"

In [20]:
df[["OLT_POWER_TX","OLT_RX_ONT_POWER","ONU_POWER_TX","ONU_POWER_RX"]].describe()

       OLT_POWER_TX  OLT_RX_ONT_POWER  ONU_POWER_TX  ONU_POWER_RX
count  20101.000000      20101.000000  20101.000000  20101.000000
mean       4.744557        -22.089401      3.679679    -17.636087
std        2.754461          8.837340      2.039322      9.181113
min       -4.780000        -40.000000      0.000000    -44.250000
25%        2.790000        -28.730000      2.360000    -24.730000
50%        4.530000        -22.260000      3.390000    -18.090000
75%        6.250000        -15.180000      4.530000    -10.350000
max       16.430000         -5.000000     10.000000      8.890000

Chaque colonne technique est analysée indépendamment

De nouvelles variables dérivées sont créées

Le dataset devient interprétable par un humain (analyse métier, visualisation)

Cette étape constitue une préparation essentielle avant la détection d’anomalies

In [21]:
def etat_valeur(v, low, high):
    if v < low:
        return "faible"
    elif v <= high:
        return "bonne"
    else:
        return "elevee"
df["Etat_OLT_TX"] = df["OLT_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 7))
df["Etat_OLT_RX"] = df["OLT_RX_ONT_POWER"].apply(lambda x: etat_valeur(x, -32, -12))
df["Etat_ONU_TX"] = df["ONU_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 5))
df["Etat_ONU_RX"] = df["ONU_POWER_RX"].apply(lambda x: etat_valeur(x, -28, -7))

/tmp/ipython-input-684765312.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_OLT_TX"] = df["OLT_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 7))
/tmp/ipython-input-684765312.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_OLT_RX"] = df["OLT_RX_ONT_POWER"].apply(lambda x: etat_valeur(x, -32, -12))
/tmp/ipython-input-684765312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_ONU_TX"] = df["ONU_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 5))
/tmp/ipython-input-684765312.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Etat_ONU_RX"] = df["ONU_POWER_RX"].apply(lambda x: etat_valeur(x, -28, -7))

Cette fonction applique une logique OR

Elle permet de détecter des anomalies partielles, fréquentes en réseau

Elle reflète une approche réaliste de la supervision proactive

In [22]:
def etat_global(row):
    if "faible" in row.values:
        return "anomalie"
    return "normal"

df["Anomalie_technique"] = df[
    ["Etat_OLT_TX","Etat_OLT_RX","Etat_ONU_TX","Etat_ONU_RX"]
].apply(etat_global, axis=1)

/tmp/ipython-input-1432877201.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Anomalie_technique"] = df[

ajouter une nouvelle colonne pour detecter l'anomalie administrative selon:

F_SUSP = 1 → ligne suspendue

ADMIN_STATUS = 1 → action administrative active

In [23]:

df["Anomalie_admin"] = np.where(
    (df["F_SUSP"] == 1) & (df["ADMIN_STATUS"] == 1),
    "Anomalie",
    "Normal"
)

/tmp/ipython-input-1836929407.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Anomalie_admin"] = np.where(

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX,Etat_OLT_TX,Etat_OLT_RX,Etat_ONU_TX,Etat_ONU_RX,Anomalie_technique,Anomalie_admin
0,80881135.0,111.0,3.0,39.0,0.0,1.0,1.0,3.80,-20.70,2.442,-20.268,bonne,bonne,bonne,bonne,normal,Normal
1,80881064.0,111.0,1.0,26.0,0.0,1.0,1.0,3.50,-20.30,2.522,-18.386,bonne,bonne,bonne,bonne,normal,Normal
4,83825624.0,111.0,13.0,60.0,0.0,1.0,1.0,3.60,-25.30,2.530,-22.840,bonne,bonne,bonne,bonne,normal,Normal
8,83847300.0,20309.0,8.0,39.0,1.0,1.0,1.0,3.60,-24.30,2.674,-23.280,bonne,bonne,bonne,bonne,normal,Anomalie
9,83109466.0,166.0,2.0,4.0,1.0,1.0,1.0,5.64,-25.86,2.330,-19.660,bonne,bonne,bonne,bonne,normal,Anomalie

ajouter une nouvelle colonne pour la detection d'anomalies globales

In [25]:

df["Anomalie"] = np.where(
    (df["Anomalie_technique"] == "Anomalie") | (df["Anomalie_admin"] == "Anomalie"),
    "Anomalie",
    "Normal"
)

df

/tmp/ipython-input-264130815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Anomalie"] = np.where(

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX,Etat_OLT_TX,Etat_OLT_RX,Etat_ONU_TX,Etat_ONU_RX,Anomalie_technique,Anomalie_admin,Anomalie
0,80881135.0,111.0,3.0,39.0,0.0,1.0,1.0,3.80,-20.70,2.442,-20.268,bonne,bonne,bonne,bonne,normal,Normal,Normal
1,80881064.0,111.0,1.0,26.0,0.0,1.0,1.0,3.50,-20.30,2.522,-18.386,bonne,bonne,bonne,bonne,normal,Normal,Normal
4,83825624.0,111.0,13.0,60.0,0.0,1.0,1.0,3.60,-25.30,2.530,-22.840,bonne,bonne,bonne,bonne,normal,Normal,Normal
8,83847300.0,20309.0,8.0,39.0,1.0,1.0,1.0,3.60,-24.30,2.674,-23.280,bonne,bonne,bonne,bonne,normal,Anomalie,Anomalie
9,83109466.0,166.0,2.0,4.0,1.0,1.0,1.0,5.64,-25.86,2.330,-19.660,bonne,bonne,bonne,bonne,normal,Anomalie,Anomalie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20879,80297925.0,20406.0,11.0,40.0,0.0,1.0,1.0,10.39,-11.24,5.250,-5.250,elevee,elevee,elevee,elevee,normal,Normal,Normal
20880,83848003.0,20727.0,16.0,91.0,0.0,0.0,0.0,1.43,-35.32,0.850,-33.680,faible,faible,faible,faible,anomalie,Normal,Normal
20881,83110199.0,20499.0,15.0,65.0,0.0,0.0,0.0,4.33,-18.69,2.740,-11.790,bonne,bonne,bonne,bonne,normal,Normal,Normal
20882,83204888.0,163.0,16.0,49.0,0.0,0.0,0.0,6.19,-26.54,2.520,-25.330,bonne,bonne,bonne,bonne,normal,Normal,Normal
20883,83825832.0,20729.0,7.0,58.0,0.0,1.0,1.0,0.82,-38.68,1.670,-29.610,faible,faible,faible,faible,anomalie,Normal,Normal

exporter la nouvelle dataset sous format xlsx qui est spécifique au la partie de visualisation

In [27]:
df.to_excel("dataset_vis.xlsx",index=False)

Ce sont de même étape que la précédente mais maintenant pour fournir une dataset spécifique au ML

In [26]:
data=pd.read_excel("XPON_QUALIF_augmented.xlsx")
data.head()

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX
0,80881135.0,111.0,3.0,39.0,0.0,1.0,1.0,3.8,-20.7,2.442,-20.268
1,80881064.0,111.0,1.0,26.0,0.0,1.0,1.0,3.5,-20.3,2.522,-18.386
2,83109348.0,151.0,1.0,3.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,83109379.0,111.0,4.0,31.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,83825624.0,111.0,13.0,60.0,0.0,1.0,1.0,3.6,-25.3,2.530,-22.840

In [28]:
data.dropna(inplace=True)

In [29]:
data = data.drop_duplicates()

In [30]:
data[["OLT_POWER_TX","OLT_RX_ONT_POWER","ONU_POWER_TX","ONU_POWER_RX"]].describe()

       OLT_POWER_TX  OLT_RX_ONT_POWER  ONU_POWER_TX  ONU_POWER_RX
count  20101.000000      20101.000000  20101.000000  20101.000000
mean       4.744557        -22.089401      3.679679    -17.636087
std        2.754461          8.837340      2.039322      9.181113
min       -4.780000        -40.000000      0.000000    -44.250000
25%        2.790000        -28.730000      2.360000    -24.730000
50%        4.530000        -22.260000      3.390000    -18.090000
75%        6.250000        -15.180000      4.530000    -10.350000
max       16.430000         -5.000000     10.000000      8.890000

In [31]:
def etat_valeur(v, low, high):
    if v < low:
        return 1
    elif v <= high:
        return 0
    else:
        return 1
data["Etat_OLT_TX"] = data["OLT_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 7))
data["Etat_OLT_RX"] = data["OLT_RX_ONT_POWER"].apply(lambda x: etat_valeur(x, -32, -12))
data["Etat_ONU_TX"] = data["ONU_POWER_TX"].apply(lambda x: etat_valeur(x, 2, 5))
data["Etat_ONU_RX"] = data["ONU_POWER_RX"].apply(lambda x: etat_valeur(x, -28, -7))

In [32]:
def etat_global(row):
    if 1 in row.values:
        return 1
    return 0

data["Anomalie_technique"] = data[
    ["Etat_OLT_TX","Etat_OLT_RX","Etat_ONU_TX","Etat_ONU_RX"]
].apply(etat_global, axis=1)

In [33]:


data["Anomalie_admin"] = np.where(
    (data["F_SUSP"] == 1) & (data["ADMIN_STATUS"] == 1),
    1,
   0
)

data

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX,Etat_OLT_TX,Etat_OLT_RX,Etat_ONU_TX,Etat_ONU_RX,Anomalie_technique,Anomalie_admin
0,80881135.0,111.0,3.0,39.0,0.0,1.0,1.0,3.80,-20.70,2.442,-20.268,0,0,0,0,0,0
1,80881064.0,111.0,1.0,26.0,0.0,1.0,1.0,3.50,-20.30,2.522,-18.386,0,0,0,0,0,0
4,83825624.0,111.0,13.0,60.0,0.0,1.0,1.0,3.60,-25.30,2.530,-22.840,0,0,0,0,0,0
8,83847300.0,20309.0,8.0,39.0,1.0,1.0,1.0,3.60,-24.30,2.674,-23.280,0,0,0,0,0,1
9,83109466.0,166.0,2.0,4.0,1.0,1.0,1.0,5.64,-25.86,2.330,-19.660,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20879,80297925.0,20406.0,11.0,40.0,0.0,1.0,1.0,10.39,-11.24,5.250,-5.250,1,1,1,1,1,0
20880,83848003.0,20727.0,16.0,91.0,0.0,0.0,0.0,1.43,-35.32,0.850,-33.680,1,1,1,1,1,0
20881,83110199.0,20499.0,15.0,65.0,0.0,0.0,0.0,4.33,-18.69,2.740,-11.790,0,0,0,0,0,0
20882,83204888.0,163.0,16.0,49.0,0.0,0.0,0.0,6.19,-26.54,2.520,-25.330,0,0,0,0,0,0
20883,83825832.0,20729.0,7.0,58.0,0.0,1.0,1.0,0.82,-38.68,1.670,-29.610,1,1,1,1,1,0

In [34]:


data["Anomalie"] = np.where(
    (data["Anomalie_technique"] == 1) | (data["Anomalie_admin"] == 1),
    1,
    0
)

data

,ID_LIGNE,ID_CARTE_OLT,NO_PORT,ONU_ID,F_SUSP,ADMIN_STATUS,OPER_STATUS,OLT_POWER_TX,OLT_RX_ONT_POWER,ONU_POWER_TX,ONU_POWER_RX,Etat_OLT_TX,Etat_OLT_RX,Etat_ONU_TX,Etat_ONU_RX,Anomalie_technique,Anomalie_admin,Anomalie
0,80881135.0,111.0,3.0,39.0,0.0,1.0,1.0,3.80,-20.70,2.442,-20.268,0,0,0,0,0,0,0
1,80881064.0,111.0,1.0,26.0,0.0,1.0,1.0,3.50,-20.30,2.522,-18.386,0,0,0,0,0,0,0
4,83825624.0,111.0,13.0,60.0,0.0,1.0,1.0,3.60,-25.30,2.530,-22.840,0,0,0,0,0,0,0
8,83847300.0,20309.0,8.0,39.0,1.0,1.0,1.0,3.60,-24.30,2.674,-23.280,0,0,0,0,0,1,1
9,83109466.0,166.0,2.0,4.0,1.0,1.0,1.0,5.64,-25.86,2.330,-19.660,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20879,80297925.0,20406.0,11.0,40.0,0.0,1.0,1.0,10.39,-11.24,5.250,-5.250,1,1,1,1,1,0,1
20880,83848003.0,20727.0,16.0,91.0,0.0,0.0,0.0,1.43,-35.32,0.850,-33.680,1,1,1,1,1,0,1
20881,83110199.0,20499.0,15.0,65.0,0.0,0.0,0.0,4.33,-18.69,2.740,-11.790,0,0,0,0,0,0,0
20882,83204888.0,163.0,16.0,49.0,0.0,0.0,0.0,6.19,-26.54,2.520,-25.330,0,0,0,0,0,0,0
20883,83825832.0,20729.0,7.0,58.0,0.0,1.0,1.0,0.82,-38.68,1.670,-29.610,1,1,1,1,1,0,1

exporter la nouvelle dataset sous format xlsx qui est spécifique au la partie de Machine Learning

In [35]:
data.to_excel("dataset_ml.xlsx",index=False)